spring.application.name=moodle

server.port=8080

# ---- Base de datos PostgreSQL (sin contraseña) ----
spring.datasource.url=jdbc:postgresql://localhost:5432/moodle_app_db
spring.datasource.username=postgres
spring.datasource.password=0942677998
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ---- Moodle REST ----
moodle.base-url=http://localhost/moodle
moodle.service-name=app_movil_service
moodle.admin-token=

# ---- JWT propio del backend ----
app.jwt.secret=g7NpD8mULHIJojtEJxsHOC7UO0E6OOl7aLhtTU9j
app.jwt.expiration-ms=86400000

logging.level.ug.sotware.moodle=DEBUG